config/routes.rb
WhatstrendingWebApp::Application.routes.draw do

  SSL_URL_OPTIONS ||= {protocol: 'https://'}
  HTTP_URL_OPTIONS ||= {protocol: 'http://'}


  # --- Require HTTPS ---
  constraints(SSL_URL_OPTIONS) do

    # ADMIN AREA
    namespace :admin do
      # A/B Testing dashboard.
      mount Split::Dashboard, at: 'ab-tests'

      get 'authors_search', to: 'users#search'

      resources :posts do
        collection do
          get 'by/:filter', to: 'posts#index', as: 'filter'
        end
        member do
          get 'publish'
          get 'unpublish'
          get 'fetch_authors'
          get 'stats/:filter', to: 'posts#stats', as: 'stats'
        end
      end
      resources :post_items, only: [:destroy] do
        get 'oembed', as: :oembed, on: :collection
      end
      resources :post_queues, only: [:create, :update]

      resources :trend_lists, path: '/trends', as: 'trends', only: [:index] do
        member do
          post 'publish'
        end
        resources :trend_list_items, path: '/list', as: 'lists', only: [] do
          resources :trend_items, path: '/item', as: 'items', only: [:edit, :update] do
            collection do
              post 'publish'
              post 'unpublish'
            end
          end
        end
      end
      resources :categories
      resources :users do
        get 'by/:filter', on: :collection, to: 'users#index', as: 'filter'
      end
      resources :badges
      resources :dashboard, only: [:index]
      resources :caches, only: [:index,:update]
      resources :layouts, only: [:index, :create]
      resources :settings, only: [:index, :create, :destroy]
      namespace :queues do
        resources :scheduled, only: [:index,:create,:destroy]
      end

      resources :search_terms, only: [:index, :show]

      root to: 'dashboard#index'
    end

    # USER ACCOUNT, SIGNUP, LOGIN, PASSWORD RESET
    resource :user, only: [:edit, :update], path: '/account', path_names: {edit: '/'}
    resource :user_session, only: [:create]
    resources :password_resets, except: [:index, :show, :destroy]
    get '/login' => 'user_sessions#new', as: :login, path: '/access/login'
    get '/logout' => 'user_sessions#destroy', as: :logout, path: '/access/logout'
  end

  # --- Require HTTP ---
  constraints(HTTP_URL_OPTIONS) do

    # ADMIN AREA
    namespace :admin do
      resources :posts, only: [] do
        member do
          match "/preview", as: :preview, action: :preview, via: [:get,:put,:post]
        end
      end
    end

    resources :email_subscribers, path: '/newsletter', only: [:new, :create], path_names: {new: 'subscribe', create: 'subscribe'}

    resources :categories, only: [:index, :show]
    resources :authors, only: [:show], path: '/contributors'
    resources :posts, only: [], path: '/post' do
      resources :post_item, only: [], as: :item, path: '/' do
        member do
          put 'share'
        end
      end
      member do 
        put 'comment'
        put 'share'
      end
    end

    resources :sharing_mails, path: '/share/email', only: [:new, :create], path_names: {new: 'send', create: 'send'} do
      get :preview, on: :collection
    end

    resources :support_messages, path: '/contact', only: [:index,:new,:create], path_names: {new: '', create: 'submit'}

    # Search path
    get '/search' => 'categories#index', as: :search, defaults: {search: true}
    get '/random' => 'posts#random', as: :random_post

    put '/_ab/:id(/:goal)' => 'ab_tests#finish', as: :finish_ab_test


    # --- OAUTH ---
    # match 'auth/:provider', to: lambda{|env| [404, {}, ["Not Found"]]}, as: 'auth', via: [:get,:post]
    # get 'auth/:provider/callback', to: 'contest/escape/authentications#create'


    if Rails.env.development?
      require 'sidekiq/web'
      mount Sidekiq::Web, at: '/sidekiq'
    end
  end

  # Protocol constrain agnostic
  root to: 'categories#index'

  # Old URL from previous WordPress Site
  get '/:year/:month/:slug' => 'posts#old', as: :old_post, constraints: {year: /\d+{4}/, month: /\d+{2}/}

  # Static pages routing, use StaticPage to check if exists as constraint
  match '/*page' => 'static_pages#show', as: :static_page, constraints: StaticPage.new, via: [:get]


  # --- OLDER CUSTOM CAMPAIGN ROUTES ---
  # Escape2Bonnaroo Contest redirect route (May 2014) - we collapsed this into a single static page after the contest ended
  get '/escapetobonnaroo/*etc', to: redirect('/escapetobonnaroo')

  # Nice SEO route for Google News
  get '/:prefix/:post_id-:slug/:id' => 'post_items#show', as: :seo_post_item, constraints: {post_id: /\d+/}
  get '/:prefix/:id-:slug' => 'posts#show', as: :seo_post, constraints: {id: /\d+/}


end


# Now this is much better!
WhatstrendingWebApp::Application.routes.named_routes.module.module_eval do
  def post_path(post, opts={})
    post_url(post, opts.merge(only_path: true) )
  end

  def post_url(post, opts={})
    seo_post_url(opts.merge(prefix: (post.category.slug rescue 'unknown'), id: ('%03d' % post.id), slug: post.slug, protocol: 'http'))
  end

  def post_item_path(post, item, opts={})
    post_item_url(post, item, opts.merge(only_path: true))
  end

  def post_item_url(post, item, opts={})
    seo_post_item_url(opts.merge(prefix: (post.category.slug rescue 'unknown'), post_id: ('%03d' % post.id), slug: post.slug, id: item.slug, protocol: 'http'))
  end

  # Social Media URLs
  def facebook_url;   'https://facebook.com/whatstrending'; end
  def twitter_url;    'https://twitter.com/whatstrending'; end
  def youtube_url;    'https://www.youtube.com/user/Whatstrending'; end
  def googleplus_url; 'https://plus.google.com/+WhatsTrending'; end
  def podcast_url;    'http://www.iheart.com/talk/show/Whats-Trending/'; end
  def instagram_url;  'http://instagram.com/whatstrending'; end
  def vine_url;       '#'; end
  def xolator_url;    'http://xolator.com?ref=wt_footer'; end
end

app/models/post_queue.rb
class PostQueue < ActiveRecord::Base

  require 'sidekiq/api'

  belongs_to :post

  validates :post, :publish_at, presence: true
  validate :publish_at_cannot_be_in_the_past

  before_save :schedule_job
  before_destroy :delete_job


  def publish_at_cannot_be_in_the_past
    if self.publish_at < Time.now
      errors.add(:publish_at, "can't be in the past")
    end
  end

  private

  def schedule_job
    delete_job unless self.jid.blank?

    if self.jid = PostQueueWorker.perform_at(self.publish_at, post_id)
      post.queue unless post.queued?
    else
      errors.add(:base, 'error occured while queuing. Please try later.')
    end
  end

  def delete_job
    if Rails.env.test?
      queue = PostQueueWorker.jobs
      queue.delete_if { |x| x['jid'] == self.jid }
    else
      queue = Sidekiq::ScheduledSet.new
      queue.each { |job| job.delete if job.jid == self.jid }
    end
  end
end

app/controllers/admin/post_queues_controller.rb
module Admin
  class PostQueuesController < BaseController

    newrelic_ignore_enduser
    load_and_authorize_resource

    def create
      @post_queue = PostQueue.new(post_queue_params)
      @post_queue.save
    end

    def update
      @post_queue = PostQueue.find(params[:id])
      @post_queue.update(post_queue_params)
      render :create
    end

    private

    def post_queue_params
      params.require(:post_queue).permit(:post_id, :publish_at)
    end
  end
end

app/helpers/post_queues_helper.rb
module PostQueuesHelper

  def round_up(time, seconds = 300)
    Time.at((time.to_f / seconds).ceil * seconds)
  end
end

app/views/admin/post_queues/_form.html.haml
= simple_form_for @post_queue, url: (@post_queue.new_record? ? admin_post_queues_url : admin_post_queue_url(@post_queue)), method: (@post_queue.new_record? ? :post : :put), remote: true do |f|
  %ul.list-unstyled.flash-msg
  = f.hidden_field :post_id
  .form-group
    #datetimepicker1.input-group.date{ 'data-date-format' => "MM/DD/YYYY hh:mm A" }
      %span.input-group-addon
        %span.glyphicon.glyphicon-calendar
      = f.text_field :publish_at, required: true, placeholder: 'MM/DD/YYYY HH:MM AM/PM', class: 'form-control', 'date-time' => true
      = f.hidden_field :publish_at, id: 'fixed_post_queue_publish_at'
  %br
  %button.btn.btn-success.pull-right{name: :commit, value: 1, type: 'submit'}= t(:publish_later)

:javascript
  $('#publish-modal-default form').on('ajax:before', function() {
    var n = new Date( $('#post_queue_publish_at').val() )
    $('#fixed_post_queue_publish_at').val( n.toUTCString() )

  }).parsley({
    validators: {
      time: function() {
        return new Date($('#post_queue_publish_at').val()) > new Date();
      }
    },
    messages: {
      time: WT.Languages.default().invalid_time
    }
  });

  $(document).on('show.bs.modal', '#publish-modal-default', function() {
    $('#datetimepicker1').data("DateTimePicker").setDate( moment.unix('#{round_up(@post_queue.publish_at || Time.now).to_i}') );
  });

app/views/admin/post_queues/_modal.html.haml
- as ||= :default
- @post_queue = @post.post_queue
- @post_queue = @post.build_post_queue if @post_queue.blank?

.modal{id: "publish-modal-#{as}", tabindex: '-1', role: 'dialog', 'aria-labelledby' => 'publishLater', 'aria-hidden' => 'true'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{'aria-hidden' => 'true', 'data-dismiss' => 'modal', type: 'button'} &times;
        %h4.modal-title= t(:publish_later)
      .modal-body
        = render '/admin/post_queues/form'
        .clearfix

app/views/admin/post_queues/create.js.haml
var $flashMsg = $('.flash-msg').removeClass('alert alert-success alert-danger');
var html = '';

var closeModal = function() {
window.location.reload()
//$('#publish-modal-default').modal('hide');
// $('.post-form').submit();
}

- if @post_queue.errors.any?
  - @post_queue.errors.full_messages.each do |msg|
    html += ("<li>#{msg}</li>");
- if @post_queue.post.errors.any?
  - @post_queue.post.errors.full_messages.each do |msg|
    html += ("<li>#{msg}</li>");

if (html == '') {
$flashMsg.addClass('alert alert-success').html('Post was queued successfully.').show()
setTimeout(function() {closeModal();},1000);
} else {
$flashMsg.addClass('alert alert-danger').html(html).show().delay(3000).fadeOut('fast');
}