config/routes.rb
WhatstrendingWebApp::Application.routes.draw do

  SSL_URL_OPTIONS ||= {protocol: 'https://'}
  HTTP_URL_OPTIONS ||= {protocol: 'http://'}


  # --- Require HTTPS ---
  constraints(SSL_URL_OPTIONS) do

    # ADMIN AREA
    namespace :admin do
      # A/B Testing dashboard.
      mount Split::Dashboard, at: 'ab-tests'

      get 'authors_search', to: 'users#search'

      resources :posts do
        collection do
          get 'by/:filter', to: 'posts#index', as: 'filter'
        end
        member do
          get 'publish'
          get 'unpublish'
          get 'fetch_authors'
          get 'stats/:filter', to: 'posts#stats', as: 'stats'
        end
      end
      resources :post_items, only: [:destroy] do
        get 'oembed', as: :oembed, on: :collection
      end
      resources :post_queues, only: [:create, :update]

      resources :trend_lists, path: '/trends', as: 'trends', only: [:index] do
        member do
          post 'publish'
        end
        resources :trend_list_items, path: '/list', as: 'lists', only: [] do
          resources :trend_items, path: '/item', as: 'items', only: [:edit, :update] do
            collection do
              post 'publish'
              post 'unpublish'
            end
          end
        end
      end
      resources :categories
      resources :users do
        get 'by/:filter', on: :collection, to: 'users#index', as: 'filter'
      end
      resources :badges
      resources :dashboard, only: [:index]
      resources :caches, only: [:index,:update]
      resources :layouts, only: [:index, :create]
      resources :settings, only: [:index, :create, :destroy]
      namespace :queues do
        resources :scheduled, only: [:index,:create,:destroy]
      end

      resources :search_terms, only: [:index, :show]

      root to: 'dashboard#index'
    end

    # USER ACCOUNT, SIGNUP, LOGIN, PASSWORD RESET
    resource :user, only: [:edit, :update], path: '/account', path_names: {edit: '/'}
    resource :user_session, only: [:create]
    resources :password_resets, except: [:index, :show, :destroy]
    get '/login' => 'user_sessions#new', as: :login, path: '/access/login'
    get '/logout' => 'user_sessions#destroy', as: :logout, path: '/access/logout'
  end

  # --- Require HTTP ---
  constraints(HTTP_URL_OPTIONS) do

    # ADMIN AREA
    namespace :admin do
      resources :posts, only: [] do
        member do
          match "/preview", as: :preview, action: :preview, via: [:get,:put,:post]
        end
      end
    end

    resources :email_subscribers, path: '/newsletter', only: [:new, :create], path_names: {new: 'subscribe', create: 'subscribe'}

    resources :categories, only: [:index, :show]
    resources :authors, only: [:show], path: '/contributors'
    resources :posts, only: [], path: '/post' do
      resources :post_item, only: [], as: :item, path: '/' do
        member do
          put 'share'
        end
      end
      member do 
        put 'comment'
        put 'share'
      end
    end

    resources :sharing_mails, path: '/share/email', only: [:new, :create], path_names: {new: 'send', create: 'send'} do
      get :preview, on: :collection
    end

    resources :support_messages, path: '/contact', only: [:index,:new,:create], path_names: {new: '', create: 'submit'}

    # Search path
    get '/search' => 'categories#index', as: :search, defaults: {search: true}
    get '/random' => 'posts#random', as: :random_post

    put '/_ab/:id(/:goal)' => 'ab_tests#finish', as: :finish_ab_test


    # --- OAUTH ---
    # match 'auth/:provider', to: lambda{|env| [404, {}, ["Not Found"]]}, as: 'auth', via: [:get,:post]
    # get 'auth/:provider/callback', to: 'contest/escape/authentications#create'


    if Rails.env.development?
      require 'sidekiq/web'
      mount Sidekiq::Web, at: '/sidekiq'
    end
  end

  # Protocol constrain agnostic
  root to: 'categories#index'

  # Old URL from previous WordPress Site
  get '/:year/:month/:slug' => 'posts#old', as: :old_post, constraints: {year: /\d+{4}/, month: /\d+{2}/}

  # Static pages routing, use StaticPage to check if exists as constraint
  match '/*page' => 'static_pages#show', as: :static_page, constraints: StaticPage.new, via: [:get]


  # --- OLDER CUSTOM CAMPAIGN ROUTES ---
  # Escape2Bonnaroo Contest redirect route (May 2014) - we collapsed this into a single static page after the contest ended
  get '/escapetobonnaroo/*etc', to: redirect('/escapetobonnaroo')

  # Nice SEO route for Google News
  get '/:prefix/:post_id-:slug/:id' => 'post_items#show', as: :seo_post_item, constraints: {post_id: /\d+/}
  get '/:prefix/:id-:slug' => 'posts#show', as: :seo_post, constraints: {id: /\d+/}


end


# Now this is much better!
WhatstrendingWebApp::Application.routes.named_routes.module.module_eval do
  def post_path(post, opts={})
    post_url(post, opts.merge(only_path: true) )
  end

  def post_url(post, opts={})
    seo_post_url(opts.merge(prefix: (post.category.slug rescue 'unknown'), id: ('%03d' % post.id), slug: post.slug, protocol: 'http'))
  end

  def post_item_path(post, item, opts={})
    post_item_url(post, item, opts.merge(only_path: true))
  end

  def post_item_url(post, item, opts={})
    seo_post_item_url(opts.merge(prefix: (post.category.slug rescue 'unknown'), post_id: ('%03d' % post.id), slug: post.slug, id: item.slug, protocol: 'http'))
  end

  # Social Media URLs
  def facebook_url;   'https://facebook.com/whatstrending'; end
  def twitter_url;    'https://twitter.com/whatstrending'; end
  def youtube_url;    'https://www.youtube.com/user/Whatstrending'; end
  def googleplus_url; 'https://plus.google.com/+WhatsTrending'; end
  def podcast_url;    'http://www.iheart.com/talk/show/Whats-Trending/'; end
  def instagram_url;  'http://instagram.com/whatstrending'; end
  def vine_url;       '#'; end
  def xolator_url;    'http://xolator.com?ref=wt_footer'; end
end

app/models/category.rb
class Category < ActiveRecord::Base

  # VARIABLES -----------------------------------------------------------------


  # EXTENSIONS ----------------------------------------------------------------

  # Awesome Nested Set
  acts_as_nested_set

  # FriendlyId
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  # Paperclip
  has_attached_file :banner_image, styles: { large: ["128x128#",:jpg], medium: ["64x64#",:jpg] }, default_style: :medium, default_url: "/images/:class/:attachment/:style.png"


  # ASSOCIATIONS --------------------------------------------------------------

  has_many :posts


  # CALLBACKS -----------------------------------------------------------------

  after_save :delete_nested_categories_set


  # VALIDATIONS ----------------------------------------------------------------

  validates :name, presence: true, length: {maximum: 250}, uniqueness: true
  validates :description, length: {maximum: 1500}, allow_blank: true, allow_nil: true
  validates_attachment :banner_image, content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] }, size: { less_than: 10.megabytes }


  # SCOPES --------------------------------------------------------------------

  scope :sfw, -> { where(nsfw: false) }
  scope :active, -> { where(active: true) }


  # CLASS METHODS -------------------------------------------------------------

  def self.delete_categories_cache(ids=[])
    Category.where(id: ids).find_each { |c| ActionController::Base.new.expire_fragment(c) }
    true
  end


  # METHODS -------------------------------------------------------------------


  def mapped_name(glue=' > ')
    self.self_and_ancestors.map(&:name).join(glue)
  end

  def level_name(mark='-')
    "#{mark * level} #{name}"
  end

  def delete_nested_categories_set
    Rails.cache.delete(['categories','nested_set_options'])
  end

end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < BaseController

    newrelic_ignore_enduser
    load_and_authorize_resource
    before_filter :load_resources, only: [:index]
    respond_to :html, :json


    def index
    end

    def show
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to admin_categories_url, notice: "Category was successfully created!"
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @category.update(category_params)
        redirect_to admin_categories_url, notice: "Category was successfully updated!"
      else
        render :edit
      end
    end

    def destroy
      @category.destroy
      redirect_to admin_categories_url, notice: "Category was successfully deleted!"
    end


  private

    def category_params
      params.require(:category).permit(:name, :description, :parent_id, :banner_image, :promotional, :nsfw, :active)
    end

    def load_resources
      @categories = []
      Category.roots.each do |root|
        @categories += root.class.associate_parents(root.self_and_descendants).compact
      end
    end

  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :load_latest_paginated_posts, if: :request_is_html
  before_filter :load_latest_wt_video_posts, only: [:index], if: :request_is_html
  before_filter :load_top_trends, if: :request_is_html


  def index
    @_per_page = request.format.xml? ? 20 : 6
    #@_offset = [(@_per_page * (@_page-1)) - 3, 0].max if %w(footer).include?(params[:place]) && request.xhr?
    #@_offset ||= nil

    results = Proc.new{|sorted|
      obj = Post.published.includes(:category).recent
      obj = obj.includes(:post_items).includes(:authors) if request.format == :xml

      # Normal search query for post
      if params[:q].present?
        obj = obj.search(params[:q])
        unless params[:q].blank?
          @search_term = SearchTerm.find_or_create_by term: params[:q].downcase
          impressionist @search_term, nil, unique: [:session_hash] rescue nil # sometimes bots spam this
        end

      # HTML / JS removes recommended items from the list
      elsif sorted
        obj = obj.unrecommended

      # XML/RSS does not rank recommended posts
      else
        obj = obj.visible_on_homepage
      end

      @posts = obj.paginate(page: @_page, per_page: @_per_page)#, offset: @_offset)
    }

    respond_to do |format|
      format.html {
        results.call(true)

        # Homepage functionality, if not a search
        if !params[:search] && @_page == 1
          load_featured_homepage_posts
          @popular_posts = Rails.cache.read(['homepage', 'popular_posts']) || []
          load_latest_posts(unrecommended: true, not: @popular_posts)

          render :home

        # Search/post pagination functionality
        else
          render :index
        end
      }
      format.js   { results.call(true) }
      format.xml  { results.call }
    end
  end

  # Individual category pages
  def show
    @category = Category.find(params[:id])
    raise ActiveRecord::RecordNotFound if @category.blank?

    @_per_page = 12

    results = Proc.new {
      @posts = Post.nested_category(@category).includes(:category).published.recent.paginate(page: @_page, per_page: @_per_page)
    }

    respond_to do |format|
      format.html { results.call }
      format.js   { results.call }
      format.xml  {
        @_per_page = 20
        results.call
      }
    end
  end


private
  
  def load_featured_homepage_posts
    @featured_posts = cache(['homepage','featured_homepage_posts'], expires_in: 5.minutes) do
      Post.published.includes(:category).recommended.weighted_homepage.all.to_a
    end
  end

end

app/views/categories/_category.html.haml
.category-list{ 'data-category' => category.slug }
  - if category.slug == 'video'
    - categories = category.children.where.not(slug: 'originals').take(3).map{|c| {id: c.id, name: c.name, slug: c.slug, posts: c.posts.published.includes(:category).recent.limit(10)} }

    %ul.pull-left.tabs.list-unstyled
      - categories.each_with_index do |c,i|
        %li= link_to c[:name], category_url(c[:slug]), 'data-tab' => c[:slug], class: (i > 0 ? '' : 'active')

    - categories.each_with_index do |c,i|
      .recent-posts.tab{'data-tab' => c[:slug], class: (i > 0 ? '' : 'open')}
        %h2= t('.latest_videos')
        %ul.list-unstyled
          - c[:posts].take(5).each do |post|
            = render 'posts/post', post: post, image: :thumbnail, format: :slide, skip: [:category], trk: wt_trk_evt(:click, :dropdown, :recent, msg: c[:slug])
        .clearfix

  - else
    - posts = Post.nested_category(category).includes(:category).published.recent.limit(12)
    - #posts = posts.where.not(id: @trending_post) unless @trending_post.blank?
    - posts = posts.shuffle unless category.slug == 'trending-now'

    - unless @trending_post.blank?
      .pull-left.trending-post
        %h2= t('.trending_post')
        %ul.list-unstyled
          = render 'posts/post', post: @trending_post, skip: [:category], format: :list_text, image: :thumbnail, trk: wt_trk_evt(:click, :dropdown, :trending, msg: category.slug)
        .clearfix
    .recent-posts
      %h2= t('.latest_posts')
      %ul.list-unstyled
        - posts.take(8).each do |post|
          = render 'posts/post', post: post, image: :thumbnail, format: :slide, skip: [:category], trk: wt_trk_evt(:click, :dropdown, :recent, msg: category.slug)
      .clearfix

  .clearfix

app/views/categories/_nav_category.html.haml
%li.dropdown{'data-category' => nav_category.slug}
  = link_to category_url(nav_category), 'data-wt-trk' => wt_trk_evt(:click, :dropdown, :nav_category, msg: nav_category.slug) do
    = nav_category.name
    - if nav_category.slug == 'video'
      %span.caret.hidden-sm

app/views/categories/_nav_category_mobile.html.haml
%li.dropdown{'data-category' => nav_category_mobile.slug}
  = link_to nav_category_mobile.name, category_url(nav_category_mobile), 'data-wt-trk' => wt_trk_evt(:click, :dropdown, :nav_category_mobile_mobile, msg: nav_category_mobile.slug)

app/views/categories/_sidebar.html.haml
- if @trend_list.present?
  .box
    .page-header
      %h3= t('.trending_now')

    %ul.trends-list.list-unstyled
      - cache([@trend_list, 'categories', 'sidebar-10'], expires_in: 15.minutes) do
        - @trend_list.take(10).each_with_index do |trend_item, i|
          = render trend_item, rank: i+1, format: :sidebar
          - if false #i == 2
            %li.page-ad
              = render 'global/ads', ad: :sidebar_upper

- if @posts && @posts.size >= 10
  .bottom-ad.page-ad
    = render 'global/ads', ad: :sidebar_lower

- unless @_page > 9
  #sidebar_footer

app/views/categories/home.html.haml
- @body_classes << 'homepage'


- content_for(:wide) do
  - cache(['homepage','all'], expires_in: 1.minute) do
    - unless @featured_posts.blank?
      #feature-area
        .inner-wrap
          .trends-list-container.col-md-2.hidden-sm.hidden-xs
            .trending-list
              %h2= t('.trending_now')
              %ul.trends-list.list-unstyled
                - cache(['homepage', @trend_list, 'homepage-3'], expires_in: 15.minutes) do
                  - unless @trend_list.blank?
                    - @trend_list[0..2].each_with_index do |trend_item, i|
                      = render trend_item, rank: i+1, format: :homepage_sidebar

          - cache(['homepage', 'featured_posts'], expires_in: 5.minutes) do
            .featured-post-container.col-sm-5.col-xs-12
              %ul.list-unstyled.posts-list
                - @featured_posts[0..0].each do |post|
                  = render post, format: :homepage_featured, trk: wt_trk_evt(:click,:homepage,:featured,'large')

            .post-grid-container.col-md-6.col-sm-7.col-xs-12
              %ul.list-unstyled.posts-list
                - @featured_posts[1..4].each do |post|
                  = render post, format: :boxed, trk: wt_trk_evt(:click,:homepage_grid,:featured)

          .clearfix

    #posts-dashboard.container-full
      .container-wrap
        .trending-list.col-md-4.hidden-sm.hidden-xs
          .page-header
            %h2= t('.trending_now')


          - unless @trend_list.blank?
            %ul.trends-list.list-unstyled.trends-list-hidden-three
              - @trend_list[0..2].each_with_index do |trend_item, i|
                = render trend_item, rank: i+1, format: :sidebar
            %ul.trends-list.list-unstyled
              - @trend_list[3..9].each_with_index do |trend_item, i|
                = render trend_item, rank: i+4, format: :sidebar
            .clearfix

        .popular-posts-list.col-md-5.col-sm-6.col-xs-12
          .page-header
            %h2= t('.popular_posts')

          - unless @popular_posts.blank?
            %ul.list-unstyled.posts-list
              - @popular_posts.shuffle[0..2].each do |post|
                = render post, format: :featured, trk: wt_trk_evt(:click,:homepage,:popular)
            .clearfix

        .latest-posts-list.col-md-3.col-sm-6.hidden-xs
          .page-header
            %h2= t('.latest_posts')

          - cache(['homepage', 'latest_posts'], expires_in: 5.minutes) do
            - unless @latest_posts.blank?
              %ul.list-unstyled.posts-list
                - @latest_posts[0..3].each do |post|
                  = render post, format: :boxed, trk: wt_trk_evt(:click,:homepage,:latest)
              .clearfix
        .clearfix

    = render 'categories/home/latest_videos'

    = render 'posts/more', posts: @posts

app/views/categories/index.html.haml
- # Search page
- if params[:q].present?
  - @body_classes << 'category'
  - @page_title = t('.searching_title', q: params[:q])
  - @page_description = t('.searching_desc', q: params[:q])
  - @page_robots_index = 'noindex'


- if params[:search]
  .content-box
    .page-header
      %h2.text-center= t(:search)

    - unless params[:q].blank?
      - unless @posts.blank?
        .page-content
          .lead= t('.searching_for', q: params[:q])
          .page-entries-info= page_entries_info(@posts, model: Post)
        %ul#posts-list.list-unstyled
          = render @posts
        .clearfix

        = will_paginate @posts, renderer: MoreButtonPagination::Rails, more_label: t(:more_search_results), page_links: false

    - if @posts.blank? || params[:q].blank?
      .page-content
        - unless params[:q].blank?
          .lead= t('.searching_for', q: params[:q])
          %p No results found. Try another search&hellip;
        - else
          .lead= t('.search')
        %form#page-search-form{action: search_url, method: :get, role: :search}
          %input{type: :text, name: :q, value: params[:q], placeholder: '', autocomplete: :off, 'data-wt-trk' => wt_trk_evt(:action, :search, :intent)}
          %button{type: :submit, value: 'Go'}
            %span.wticon.wticon-search

- else
  - # PAGINATED LIST
  .content-box
    .page-header
      %h3
        = t('.latest_posts')
        - unless @_page == 1
          %small= t('.page', page: @_page)
      .clearfix

    - unless @posts.blank?
      - # POSTS LIST
      %ul#posts-list.posts-list.list-unstyled
        - @posts.each_with_index do |post, i|
          - # TODO : EVENTUAL INLINE PLACEMENT OF ADS
          = render post, has: [:share]
      .clearfix

      .text-center
        = will_paginate @posts, renderer: MoreButtonPagination::Rails, page_links: false

app/views/categories/index.js.haml
$('#posts-list').append($('#{j render(@posts, has: [:share])}'));
- if @posts.next_page
  $('.pagination').replaceWith('#{j will_paginate(@posts, renderer: MoreButtonPagination::Rails, page_links: false)}');
  $('.page-entries-info').replaceWith('#{j page_entries_info(@posts)}');
- else
  $('.pagination').remove();
$(window).trigger('preload:images')

app/views/categories/show.html.haml
- @body_classes << 'category'
- @page_title = t('categories.show.page_title', name: @category.name)
- @page_description = @category.description
- @page_keywords = @category.name.downcase
- @page_canonical_url = category_url(@category)


.content-box
  .page-header
    %h2
      = @category.name
      - unless @_page == 1
        %small= t('.page', page: @_page)

  - unless true #@category.description.blank?
    .page-content
      .lead= @category.description

    .clearfix

  %ul#posts-list.list-unstyled
    = render @posts, skip: [:category]
  .clearfix

  = will_paginate @posts, renderer: MoreButtonPagination::Rails, more_label: t(:more_label, item: @category.name), page_links: false

app/views/categories/show.js.haml
$('#posts-list').append($('#{j render(@posts, skip: [:category])}'))
- if @posts.next_page
  $('.pagination').replaceWith('#{j will_paginate(@posts, renderer: MoreButtonPagination::Rails, more_label: t(:more_label, item: @category.name), page_links: false)}');
- else
  $('.pagination').remove();
$(window).trigger('preload:images')